# Generated by Django 4.1 on 2022-08-15 17:44

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recipes', '0002_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ingridient',
            name='measurement_unit',
            field=models.CharField(max_length=200),
        ),
        migrations.AlterField(
            model_name='ingridient',
            name='name',
            field=models.CharField(max_length=200),
        ),
        migrations.AlterField(
            model_name='recipe',
            name='cooking_time',
            field=models.IntegerField(validators=[django.core.validators.MinValueValidator(1, message='Время приготовления не может быть меньше 1')]),
        ),
        migrations.AlterField(
            model_name='recipeingridients',
            name='weight',
            field=models.IntegerField(validators=[django.core.validators.MinValueValidator(0.0, message='Значение не может быть меньше 0')]),
        ),
    ]
